name: Latest activity

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:

    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://dev.to/feed/krusty93"
          commit_message: "Updates README.md with latest dev.to blog posts"

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW"
          feed_list: "https://stackoverflow.com/feeds/user/3415073"
          commit_message: "Updates README.md with latest StackOverflow activity"